version: 2
updates:
    # Fetch and update latest `npm` packages
    - package-ecosystem: npm
      directory: "/"
      target-branch: dev
      schedule:
          interval: daily
          time: "00:00"
      open-pull-requests-limit: 10
      reviewers:
          - anatoleam
          - melonify
      assignees:
          - anatoleam
          - melonify
      commit-message:
          prefix: fix
          prefix-development: chore
          include: scope
    # Fetch and update latest `github-actions` pkgs
    - package-ecosystem: github-actions
      directory: "/"
      target-branch: dev
      schedule:
          interval: daily
          time: "00:00"
      open-pull-requests-limit: 10
      reviewers:
          - anatoleam
          - melonify
      assignees:
          - anatoleam
          - melonify
      commit-message:
          prefix: fix
          prefix-development: chore
          include: scope
